version: '3.9'

services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: on-failure
    
    client:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on: 
            - backend