// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1440, 815));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'San Diego']")).click();
    }
    vars.put("city1Selected", driver.findElement(By.name("fromPort")).getAttribute("value"));
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'London']")).click();
    }
    vars.put("city2Selected", driver.findElement(By.name("toPort")).getAttribute("value"));
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")).click();
    vars.put("AirlineSelected", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")).getText());
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5)")).click();
    driver.findElement(By.cssSelector("th:nth-child(4)")).click();
    assertThat(driver.findElement(By.cssSelector("th:nth-child(4)")).getText(), is("Departs: vars.get(\"city1Selected\").toString()"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5)")).click();
    driver.findElement(By.cssSelector("th:nth-child(5)")).click();
    driver.findElement(By.cssSelector("th:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector("th:nth-child(5)")).getText(), is("Arrives: vars.get(\"city2Selected\").toString()"));
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(6)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(7)")).click();
    vars.put("priceSelected", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(7)")).getText());
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)")).click();
    vars.put("flightNumber", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)")).getText());
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Airline: vars.get(\"AirlineSelected\").toString()"));
    driver.findElement(By.cssSelector("p:nth-child(5)")).click();
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Flight Number: vars.get(\"flightNumber\").toString()"));
    driver.findElement(By.cssSelector("p:nth-child(4)")).click();
    driver.findElement(By.cssSelector("p:nth-child(4)")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4)")).getText(), is("Price: vars.get(\"priceSelected\").toString()"));
    driver.findElement(By.cssSelector(".container:nth-child(2)")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Carl");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("123 Main St.");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Diego");
    driver.findElement(By.id("state")).click();
    driver.findElement(By.id("state")).sendKeys("California");
    driver.findElement(By.id("zipCode")).click();
    driver.findElement(By.id("zipCode")).sendKeys("45234");
    driver.findElement(By.id("cardType")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(8) > .controls")).click();
    driver.findElement(By.id("creditCardNumber")).click();
    driver.findElement(By.id("creditCardNumber")).sendKeys("233242422424");
    driver.findElement(By.id("creditCardMonth")).click();
    driver.findElement(By.id("creditCardMonth")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("nameOnCard")).click();
    driver.findElement(By.id("nameOnCard")).sendKeys("Carl Johnson");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(2)")).click();
    assertThat(driver.getTitle(), is("BlazeDemo Confirmation"));
  }
}
