// Generated by Selenium IDE
package com.tqs;

import org.apache.tomcat.jni.Time;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;
public class Lab4_2_Test1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private WebDriverWait wait;
  private Actions act;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    wait = new WebDriverWait(driver, Duration.ofSeconds(5));
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() throws InterruptedException {
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1440, 815));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'San Diego']")).click();
    }
    vars.put("city1Selected", driver.findElement(By.name("fromPort")).getAttribute("value"));
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'London']")).click();
    }
    vars.put("city2Selected", driver.findElement(By.name("toPort")).getAttribute("value"));
    
    WebElement element = driver.findElement(By.cssSelector(".btn-primary"));
    act = new Actions(driver);
    //element= wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-primary")));
    act.moveToElement(element).click().perform();
    //element.click();
    
    element = driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)"));
    act.moveToElement(element).click().perform();
    // element= wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")));
    // element.click();

    TimeUnit.SECONDS.sleep(5);
    //driver.findElement(By.id("inputName")).click();
    element = driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)"));
    act.moveToElement(element).perform();
    element.click();
    //element= wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//tr[2]/td[2]")));
    //element.click(); //Mudei

    element = driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)"));
    act.moveToElement(element).click().perform();
    //driver.findElement(By.id("address")).click();
    //HERE
    // element= wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")));
    // element.click();

    vars.put("AirlineSelected", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")).getText());
    //vars.put("AirlineSelected", driver.findElement(By.id("address")).getText());
    element = driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5)"));
    act.moveToElement(element).click().perform();
    element = driver.findElement(By.cssSelector("th:nth-child(4)"));
    act.moveToElement(element).click().perform();
    assertThat(driver.findElement(By.cssSelector("th:nth-child(4)")).getText()).isEqualTo("Departs: vars.get(\"city1Selected\").toString()");
    element = driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5)"));
    act.moveToElement(element).click().perform();
    element = driver.findElement(By.cssSelector("th:nth-child(5)"));
    act.moveToElement(element).click().perform();
    element = driver.findElement(By.cssSelector("th:nth-child(5)"));
    act.moveToElement(element).click().perform();
    assertThat(driver.findElement(By.cssSelector("th:nth-child(5)")).getText()).isEqualTo("Arrives: vars.get(\"city2Selected\").toString()");
    element = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(6)"));
    act.moveToElement(element).click().perform();
    element = driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(7)"));
    act.moveToElement(element).click().perform();
    vars.put("priceSelected", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(7)")).getText());
    element = driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)"));
    act.moveToElement(element).click().perform();
    vars.put("flightNumber", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)")).getText());
    element = driver.findElement(By.cssSelector("tr:nth-child(2) .btn"));
    act.moveToElement(element).click().perform();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText()).isEqualTo("Airline: vars.get(\"AirlineSelected\").toString()");
    element = driver.findElement(By.cssSelector("p:nth-child(5)"));
    act.moveToElement(element).click().perform();
    element = driver.findElement(By.cssSelector("p:nth-child(3)"));
    act.moveToElement(element).click().perform();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText()).isEqualTo("Flight Number: vars.get(\"flightNumber\").toString()");
    element = driver.findElement(By.cssSelector("p:nth-child(4)"));
    act.moveToElement(element).click().perform();
    element = driver.findElement(By.cssSelector("p:nth-child(4)"));
    act.moveToElement(element).click().perform();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4)")).getText()).isEqualTo("Price: vars.get(\"priceSelected\").toString()");
    driver.findElement(By.cssSelector(".container:nth-child(2)")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Carl");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("123 Main St.");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Diego");
    driver.findElement(By.id("state")).click();
    driver.findElement(By.id("state")).sendKeys("California");
    driver.findElement(By.id("zipCode")).click();
    driver.findElement(By.id("zipCode")).sendKeys("45234");
    driver.findElement(By.id("cardType")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(8) > .controls")).click();
    driver.findElement(By.id("creditCardNumber")).click();
    driver.findElement(By.id("creditCardNumber")).sendKeys("233242422424");
    driver.findElement(By.id("creditCardMonth")).click();
    driver.findElement(By.id("creditCardMonth")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("nameOnCard")).click();
    driver.findElement(By.id("nameOnCard")).sendKeys("Carl Johnson");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(2)")).click();
    assertThat(driver.getTitle()).isEqualTo("BlazeDemo Confirmation");
  }
}
